<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AI\yolo26n.onnx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AI\yolo26n.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="System.Numerics.Tensors" Version="10.0.12" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
  </ItemGroup>

</Project>
